name: Editor tests
on:
  pull_request:
  push:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ATOM_JASMINE_REPORTER: list

jobs:
  tests:
    name: Tests
    if: |
      !startsWith(github.event.pull_request.title, '[skip-ci]') &&
      !startsWith(github.event.pull_request.title, '[skip-editor-ci]')
    strategy:
      matrix:
        # os: [ubuntu-20.04, macos-13, windows-2019]
        os: [ubuntu-latest, macos-14]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install build dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libx11-dev libxkbfile-dev pkg-config libsecret-1-dev libncursesw5-dev libgdbm-dev libc6-dev libffi-dev libwayland-dev libxkbcommon-dev libxkbcommon-x11-dev libxkbcommon0 xkb-data

    - name: Checkout the latest code
      uses: actions/checkout@v5
      with:
        submodules: true
    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: 16

    - name: Install Python setuptools
      # This is needed for Python 3.12+, since many versions of node-gyp
      # are incompatible with Python 3.12+, which no-longer ships 'distutils'
      # out of the box. 'setuptools' package provides 'distutils'.
      run: python3 -m pip install setuptools --break-system-packages

    - name: Install Dependencies
      run: yarn install --ignore-engines || yarn install --ignore-engines

    - name: Build Dependencies
      run: yarn build

    - name: Run Tests
      if: runner.os != 'Linux'
      run: yarn start --test spec

    - name: Run Tests with xvfb-run (Linux)
      if: runner.os == 'Linux'
      run: xvfb-run --auto-servernum yarn start --test spec
